/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.view;

import java.awt.HeadlessException;
import javax.swing.DefaultListModel;
import project.model.Cursos;
import project.model.Disciplinas;
import project.model.Turmas;
import javax.swing.JOptionPane;
import project.connection.ConectionSingleton;
import project.enuns.Situation;
import project.model.Docentes;
import project.repository.Tipo;
import project.repository.TurmaDAO;

/**
 *
 * @author Yara
 * 
 */
public class CadastroTurma extends javax.swing.JFrame {
    Turmas turma = null;
    Disciplinas disciplina = null;
    Docentes cood =null;
    Tipo persist;
    DefaultListModel model;
    
    /**
     * Creates new form CadastroTurma
     */
    public CadastroTurma() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void CarregarComboBoxes() {
        horarios.removeAllItems();
        semana.removeAllItems();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoCurso = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        salvar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        semestre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        horarios = new javax.swing.JComboBox<>();
        semana = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        nomeTurma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IDturma = new javax.swing.JTextField();
        IDdisciplina = new javax.swing.JTextField();
        BuscarIdTruma = new javax.swing.JButton();
        BuscarIdDisciplina2 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Dados Turma: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Turmas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );

        jLabel1.getAccessibleContext().setAccessibleName("cadastroTurmas");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(null);

        salvar.setBackground(new java.awt.Color(51, 255, 51));
        salvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salvar.setText("Salvar");
        salvar.setBorderPainted(false);
        salvar.setFocusPainted(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jPanel2.add(salvar);
        salvar.setBounds(460, 300, 90, 26);

        Voltar.setBackground(new java.awt.Color(255, 51, 0));
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setText("Voltar");
        Voltar.setBorderPainted(false);
        Voltar.setFocusPainted(false);
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel2.add(Voltar);
        Voltar.setBounds(189, 302, 100, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Semestre:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(400, 110, 60, 30);
        jPanel2.add(semestre);
        semestre.setBounds(470, 110, 100, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Ano:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(420, 160, 30, 30);

        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });
        jPanel2.add(ano);
        ano.setBounds(470, 160, 100, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Disciplinas:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 60, 59, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Horarios:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(110, 110, 48, 30);

        horarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:45 a 11:50", "13:45 a 17:50", "18:45 a 11:50" }));
        horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horariosActionPerformed(evt);
            }
        });
        jPanel2.add(horarios);
        horarios.setBounds(170, 110, 150, 30);

        semana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "segunda a sexta", "segunda a sabado" }));
        semana.setToolTipText("");
        semana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanaActionPerformed(evt);
            }
        });
        jPanel2.add(semana);
        semana.setBounds(170, 160, 150, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Dias da semana:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 160, 85, 30);

        nomeTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTurmaActionPerformed(evt);
            }
        });
        jPanel2.add(nomeTurma);
        nomeTurma.setBounds(470, 60, 100, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(400, 60, 70, 30);
        jPanel2.add(IDturma);
        IDturma.setBounds(220, 20, 50, 20);

        IDdisciplina.setText("jTextField1");
        jPanel2.add(IDdisciplina);
        IDdisciplina.setBounds(170, 60, 120, 30);

        BuscarIdTruma.setText("BuscarTruma");
        BuscarIdTruma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIdTrumaActionPerformed(evt);
            }
        });
        jPanel2.add(BuscarIdTruma);
        BuscarIdTruma.setBounds(270, 10, 160, 30);

        BuscarIdDisciplina2.setText("...");
        BuscarIdDisciplina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIdDisciplina2ActionPerformed(evt);
            }
        });
        jPanel2.add(BuscarIdDisciplina2);
        BuscarIdDisciplina2.setBounds(290, 60, 43, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 680, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        CadastroTurma d = new CadastroTurma();
        setVisible(false);
        SecretariaP f = new SecretariaP ();
        f.setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        persist = new Tipo(new TurmaDAO((ConectionSingleton.getEntity())));
        try {

            if (isInsert()) {

                turma = unir();
                persist.save(disciplina);
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
            } else {
                turma = persist.find(Integer.parseInt(IDturma.getText()));
                atualizar(turma);
                persist.update(turma);
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_salvarActionPerformed

    private void horariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horariosActionPerformed
        horarios.addItem("08:45  11:50");
        horarios.addItem("13:45  17:50");
        horarios.addItem("18:45  22:50");
    }//GEN-LAST:event_horariosActionPerformed

    private void semanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanaActionPerformed
        semana.addItem("seguda a sexta");
        semana.addItem("seguda a sabado");
        
    }//GEN-LAST:event_semanaActionPerformed

    private void nomeTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTurmaActionPerformed

    private void BuscarIdTrumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIdTrumaActionPerformed
        // TODO add your handling code here:
        ConsultarTurma t = new ConsultarTurma(this);
        t.setVisible(true);
    }//GEN-LAST:event_BuscarIdTrumaActionPerformed

    private void BuscarIdDisciplina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIdDisciplina2ActionPerformed
        // TODO add your handling code here:
        ConsultarDisciplina f = new ConsultarDisciplina();
        f.setVisible(true);
    }//GEN-LAST:event_BuscarIdDisciplina2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTurma().setVisible(true);
            }
        });
    }
    public void dadosID(Disciplinas disciplinas) {
        IDdisciplina.setText(disciplinas.getId_disciplina().toString());
        
    }
     public boolean isInsert() {
        String id = IDturma.getText();
        return id.isEmpty();
    }
     public void atualizar(Turmas turma) {

        turma.setDiscricao(nomeTurma.getText());
        turma.setHorario(Integer.parseInt(horarios.getSelectedItem().toString()));
        turma.setDiasSemana(semana.getSelectedItem().toString());
        turma.setAnoSemestre(semestre.getText());
        turma.setAnoSemestre(ano.getText());
        turma.setDisciplina(disciplina);
        turma.setProfessorResponsavel(cood);
    }
     
    public Turmas unir() {
        String descricaoTurma = nomeTurma.getText();
        Integer horario = Integer.parseInt(horarios.getSelectedItem().toString());
        String diaSemana = semana.getSelectedItem().toString();
        String semestres = semestre.getText();
        String anos = ano.getText();
        Turmas d = new Turmas(0, diaSemana, diaSemana, semestres);
        persist = new Tipo(new TurmaDAO((ConectionSingleton.getEntity())));

        return d;
    } 
     public void dados(Turmas turma) {
        IDturma.setText(turma.getIdTurma().toString());
        nomeTurma.setText(turma.getDiscricao());
        semana.setSelectedItem(turma.getDiasSemana());
        horarios.setSelectedItem(turma.getHorario());
        semestre.setText(turma.getAnoSemestre());
        ano.setText(turma.getAnoSemestre());

    }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarIdDisciplina2;
    private javax.swing.JButton BuscarIdTruma;
    private javax.swing.JTextField IDdisciplina;
    private javax.swing.JTextField IDturma;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField ano;
    private javax.swing.JComboBox<String> horarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nomeTurma;
    private javax.swing.JButton salvar;
    private javax.swing.JComboBox<String> semana;
    private javax.swing.JTextField semestre;
    private javax.swing.JComboBox<String> tipoCurso;
    // End of variables declaration//GEN-END:variables
}
