/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.view;

import java.awt.HeadlessException;
import project.model.Cursos;
import project.enuns.TipoCurso;
import javax.swing.JOptionPane;
import project.connection.ConectionSingleton;
import project.repository.CursoDAO;
import project.repository.Tipo;

/**
 *
 * @author Yara
 */
public class CadastroCurso extends javax.swing.JFrame {
    Cursos Curso = null;
    Tipo persist;
    /**
     * Creates new form CadastroCurso
     */
    public CadastroCurso() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
        public CadastroCurso(Cursos curso) {
        initComponents();
        dados(curso);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomeCurs = new javax.swing.JLabel();
        nomeCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        ativo = new javax.swing.JToggleButton();
        inativo = new javax.swing.JToggleButton();
        cood = new javax.swing.JButton();
        jComboBoxtipoCurso = new javax.swing.JComboBox<>();
        jButtonCadastroBuscarIdCurso1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Curso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Código:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        nomeCurs.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nomeCurs.setText("Nome do Curso:");
        jPanel2.add(nomeCurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 30));

        nomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCursoActionPerformed(evt);
            }
        });
        jPanel2.add(nomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Descrição:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Professor Coordenador:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Tipo de Curso:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        salvar.setBackground(new java.awt.Color(51, 255, 51));
        salvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salvar.setForeground(new java.awt.Color(0, 0, 0));
        salvar.setText("Salvar");
        salvar.setBorderPainted(false);
        salvar.setFocusPainted(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jPanel2.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 100, -1));

        voltar.setBackground(new java.awt.Color(255, 51, 0));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.setBorderPainted(false);
        voltar.setFocusPainted(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel2.add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, -1));

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 30));

        ativo.setText("ativo");
        ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativoActionPerformed(evt);
            }
        });
        jPanel2.add(ativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        inativo.setText("inativo");
        inativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inativoActionPerformed(evt);
            }
        });
        jPanel2.add(inativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        cood.setText("...");
        cood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coodActionPerformed(evt);
            }
        });
        jPanel2.add(cood, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 30));

        jComboBoxtipoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRADUAÇAO", "PROS GRADUAÇAO", "MESTRADO", "DOUTORADO" }));
        jComboBoxtipoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtipoCursoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxtipoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 120, -1));

        jButtonCadastroBuscarIdCurso1.setText("...");
        jButtonCadastroBuscarIdCurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroBuscarIdCurso1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCadastroBuscarIdCurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 50, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 580, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void nomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCursoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
       persist = new Tipo(new CursoDAO ((ConectionSingleton.getEntity())));

        try {
            if (isInsert()) {
                Curso = unir();
                persist.save(Curso);
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
            } else {
                Curso = persist.find(Integer.parseInt(ID.getText()));
                atualizar(Curso);
                persist.update(Curso);
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void coodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coodActionPerformed
        // TODO add your handling code here:
        CadastroCurso f = new CadastroCurso();
        f.setVisible(true);
    }//GEN-LAST:event_coodActionPerformed

    private void inativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inativoActionPerformed
        inativo.setSelected(false);
    }//GEN-LAST:event_inativoActionPerformed

    private void ativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativoActionPerformed
        ativo.setSelected(false);
    }//GEN-LAST:event_ativoActionPerformed

    private void jComboBoxtipoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtipoCursoActionPerformed
        // TODO add your handling code here:
        jComboBoxtipoCurso.addItem("Graduaçao");
        jComboBoxtipoCurso.addItem("pos");
        jComboBoxtipoCurso.addItem("mestrado");
        jComboBoxtipoCurso.addItem("doutorado");
        
    }//GEN-LAST:event_jComboBoxtipoCursoActionPerformed

    private void jButtonCadastroBuscarIdCurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroBuscarIdCurso1ActionPerformed
        // TODO add your handling code here:
        ConsultarProfessor p = new ConsultarProfessor();
        p.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroBuscarIdCurso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCurso().setVisible(true);
            }
        });
    }

        public boolean isInsert() {
        String id = ID.getText();
        return id.isEmpty();
    }
        
        public void atualizar(Cursos curso) {
        curso.setId_curso(Integer.parseInt(ID.getText()));
        curso.setDescricao(nomeCurso.getText());
      
    }
        
    public Cursos unir() {
        String descricao = nomeCurso.getText();
        //Integer codCoordenador = Integer.parseInt(jTextCadastroIdCoordenador.getText());
        Integer coordenador = 5;
        char situacao = (ativo.isSelected() ? 'S' : 'N');

        return new Cursos(descricao, coordenador, situacao);
    }
    
    public void dados(Cursos curso) {
        ID.setText(curso.getId_curso().toString());
        nomeCurso.setText(curso.getDescricao().toString());
        if (curso.getStatus()== 'S') {
            ativo.setSelected(true);
        } else {
            inativo.setSelected(true);
        }
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JToggleButton ativo;
    private javax.swing.JButton cood;
    private javax.swing.JToggleButton inativo;
    private javax.swing.JButton jButtonCadastroBuscarIdCurso1;
    private javax.swing.JComboBox<String> jComboBoxtipoCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomeCurs;
    private javax.swing.JTextField nomeCurso;
    private javax.swing.JButton salvar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
