/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.view;

import project.model.Turmas;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.connection.ConectionSingleton;
import project.model.Alunos;
import project.repository.AlunoDAO;
import project.repository.Tipo;

/**
 *
 * @author Yara Sereia do Cerrado
 */
public class ConsultarAlunos extends javax.swing.JFrame {
    Tipo persist;
    /**
     * Creates new form ConsultarAlunos
     */

    public ConsultarAlunos() {
        initComponents();
        persist = new Tipo(new AlunoDAO((ConectionSingleton.getEntity())));
        getListAlunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Alunos ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAlunos.setBackground(new java.awt.Color(0, 0, 0));
        jTableAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome", "Telefone", "Curso"
            }
        ));
        jTableAlunos.setFocusable(false);
        jTableAlunos.setGridColor(new java.awt.Color(255, 255, 255));
        jTableAlunos.setName(""); // NOI18N
        jTableAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableAlunosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlunos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 590, 280));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CadastroAluno mCadastrosAlunos = new CadastroAluno();
        mCadastrosAlunos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableAlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlunosMousePressed

        if (evt.getClickCount() == 2) {
            int matricula = Integer.parseInt(jTableAlunos.getValueAt(jTableAlunos.getSelectedRow(), 0).toString());
            CadastroAluno sCadastrosAlunos = new CadastroAluno (montarAlunoSelecionado(matricula));
            sCadastrosAlunos.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTableAlunosMousePressed

    /**
     * @param args the command line arguments
     */

        public void getListAlunos() {
        
        List<Alunos> list = persist.lista();

        for (Alunos aluno : list) {

            DefaultTableModel model = (DefaultTableModel) jTableAlunos.getModel();

            String[] aux = new String[4];
            aux[0] = aluno.getId_person().toString();
            aux[1] = aluno.getNomeUsuario();
            aux[2] = aluno.getTelefoneUsuario();
            aux[3] = aluno.getIdcurso().toString();
            model.addRow(aux);
        }
    }
    
    public Alunos montarAlunoSelecionado(int id){
        
        return persist.find(id);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlunos;
    // End of variables declaration//GEN-END:variables
}
