/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.view;


import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Yara
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(boolean secretaria, boolean professor, boolean coordenacao, boolean recursosHumanos, boolean aluno) {
        initComponents();
        menuAluno.setVisible(aluno);
        menuCordenador.setVisible(coordenacao);
        menuProfessor.setVisible(professor);
        menuRh.setVisible(recursosHumanos);
        menuSecretaria.setVisible(secretaria);
    }

    Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuSecretaria = new javax.swing.JButton();
        jData = new javax.swing.JLabel();
        menuProfessor = new javax.swing.JButton();
        menuRh = new javax.swing.JButton();
        menuAluno = new javax.swing.JButton();
        menuCordenador = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuSecretaria.setBackground(new java.awt.Color(255, 255, 102));
        menuSecretaria.setForeground(new java.awt.Color(0, 0, 0));
        menuSecretaria.setText("Secretaria");
        menuSecretaria.setBorderPainted(false);
        menuSecretaria.setFocusPainted(false);
        menuSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSecretariaActionPerformed(evt);
            }
        });
        getContentPane().add(menuSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 160, 40));

        jData.setBackground(new java.awt.Color(0, 255, 255));
        jData.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        jData.setForeground(new java.awt.Color(255, 255, 0));
        jData.setText("dd/MM/yyyy");
        getContentPane().add(jData, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 240, 60));

        menuProfessor.setBackground(new java.awt.Color(255, 255, 102));
        menuProfessor.setForeground(new java.awt.Color(0, 0, 0));
        menuProfessor.setText("Professor");
        menuProfessor.setBorderPainted(false);
        menuProfessor.setFocusPainted(false);
        menuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(menuProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 160, 40));

        menuRh.setBackground(new java.awt.Color(255, 255, 102));
        menuRh.setForeground(new java.awt.Color(0, 0, 0));
        menuRh.setText("Rh");
        menuRh.setBorderPainted(false);
        menuRh.setFocusPainted(false);
        menuRh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRhActionPerformed(evt);
            }
        });
        getContentPane().add(menuRh, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 160, 40));

        menuAluno.setBackground(new java.awt.Color(255, 255, 102));
        menuAluno.setForeground(new java.awt.Color(0, 0, 0));
        menuAluno.setText("Aluno");
        menuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(menuAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, 40));

        menuCordenador.setBackground(new java.awt.Color(255, 255, 102));
        menuCordenador.setForeground(new java.awt.Color(0, 0, 0));
        menuCordenador.setText("Coordenador");
        menuCordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCordenadorActionPerformed(evt);
            }
        });
        getContentPane().add(menuCordenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 160, 40));

        sair.setText("sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1010, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        
        Date dataS = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy   HH: mm: ss ");
        jData.setText(formato.format(dataS));
  
       // jHora.setText(String.format("hh: mm: ss: aa",timer.obtenerHora()));
        
    }//GEN-LAST:event_formWindowOpened

    private void menuSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSecretariaActionPerformed
        // TODO add your handling code here:
        SecretariaP m = new SecretariaP();
        m.setVisible(true);
    }//GEN-LAST:event_menuSecretariaActionPerformed

    private void menuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfessorActionPerformed
        // TODO add your handling code here:
       ProfessorPerspective n = new ProfessorPerspective();
        n.setVisible(true);
    }//GEN-LAST:event_menuProfessorActionPerformed

    private void menuRhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRhActionPerformed
        // TODO add your handling code here:
        RHPerspective p = new RHPerspective();
         p.setVisible(true);
    }//GEN-LAST:event_menuRhActionPerformed

    private void menuCordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCordenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCordenadorActionPerformed

    private void menuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlunoActionPerformed
        // TODO add your handling code here:
        StudentPerspective  c = new StudentPerspective();
        c.setVisible(true);
    }//GEN-LAST:event_menuAlunoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here: 
               System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton menuAluno;
    private javax.swing.JButton menuCordenador;
    private javax.swing.JButton menuProfessor;
    private javax.swing.JButton menuRh;
    private javax.swing.JButton menuSecretaria;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
