package project.view;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import project.connection.ConectionSingleton;
import project.controller.DocentesControle;
import project.enuns.Departamento;
import project.enuns.Perfil;
import project.enuns.TipoCurso;
import project.model.Docentes;
import project.repository.DocentesDAO;
import project.repository.Tipo;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yara
 *
 */
public class RHPerspective extends javax.swing.JFrame {
    Docentes docente =null;
    Tipo persist ;
    ConectionSingleton d = (ConectionSingleton) (ConectionSingleton.getEntity());
    
    /**
     * Creates new form NewJFrame
     */
    
    


    public RHPerspective() {
        initComponents();
        persist = new Tipo(new DocentesDAO((ConectionSingleton.getEntity())));
        this.preencherCombos();
    }
    
     public RHPerspective(Integer idFuncionario) {
        initComponents();
        this.preencherCombos();
        this.preencherDadosTela(idFuncionario);
    }
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbTitulacao = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salvar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        ID = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox<>();
        idFuncionario = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Cidade:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        nome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 358, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Endereço:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        endereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 358, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        telefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 358, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Titulação:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        cmbTitulacao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbTitulacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Especialização", "Mestrado", "Doutorado" }));
        getContentPane().add(cmbTitulacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 358, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Endereço", "Telefone", "Titulação", "Cursos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 730, 140));

        salvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        salvar.setText("Cadastrar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        voltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        ID.setText("Buscar");
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 80, 20));

        jLabel14.setText("Departamento:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, 40));

        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Especialização", "Mestrado", "Doutorado" }));
        cmbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jLabel17.setText("Perfil:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, 40));

        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Especialização", "Mestrado", "Doutorado" }));
        cmbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));
        getContentPane().add(idFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 70, -1));

        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        getContentPane().add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 360, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel6.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Recursos Humanos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel6)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
        ConsultarProfessor funConsulta = new ConsultarProfessor(d.getEntity());
        funConsulta.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_IDActionPerformed

    private void cmbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartamentoActionPerformed

    private void cmbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPerfilActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        persist = new Tipo(new DocentesDAO((ConectionSingleton.getEntity())));
        try {
            if (isInsert()) {
                docente = unir();
                persist.save(docente);
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
            } else {
                docente = persist.find(Integer.parseInt(idFuncionario.getText()));
                 atualizar(docente);
                persist.update(docente);
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        
    }//GEN-LAST:event_salvarActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here
        Menu f = new Menu();
        f.setVisible(true);
    }//GEN-LAST:event_cidadeActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_voltarActionPerformed
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RHPerspective().setVisible(true);
            }
        });
    }
    
    
    
    public boolean isInsert() {
        String id = idFuncionario.getText();
        return id.isEmpty();
    }
    
    public Departamento verificarDepartamento(String itemSelcionado) {
        switch (itemSelcionado.trim()) {
            case "ACADEMICO":
                return Departamento.ACADEMICO;

            case "RECURSOS_HUMANOS":
                return Departamento.RECURSOS_HUMANOS;

            case "SECRETARIA":
                return Departamento.SECRETARIA;
            default:
                return null;
        }
    }
    public Perfil verificarPerfil(String itemSelcionado) {
        switch (itemSelcionado.trim()) {
            case "ADMIN":
                return Perfil.ADMIN;
            case "ALUNO":
                return Perfil.ALUNO;
            case "COORDENACAO":
                return Perfil.COORDENADOR;
            case "PROFESSOR":
                return Perfil.PROFESSOR;
            case "RECURSOSHUMANOS":
                return Perfil.RECURSOS_HUMANOS;
            case "SECRETARIA":
                return Perfil.SECRETARIA;
            case "SEMACESSO":
 
            default:
                return null;
        }
    }
     public TipoCurso verificarTitulacao(String itemSelcionado) {
        switch (itemSelcionado.trim()) {
            case "DOUTOR":
                return TipoCurso.DOUTOR;
            case "ENS_FUNDAMENTAL":
                return TipoCurso.ENS_FUNDAMENTAL;
            case "ENS_MEDIO":
                return TipoCurso.ENS_MEDIO;
            case "GRADUADO":
                return TipoCurso.GRADUADO;
            case "MESTRE":
                return TipoCurso.MESTRE;
            case "PHD":
                return TipoCurso.PHD;
            case "POS_GRADUADO":
                return TipoCurso.POS_GRADUADO;
            default:
                return null;
        }
        
    }
    public void atualizar(Docentes docente){
            docente.setNomeUsuario(nome.getText());
            docente.setCidadeUsuario(cidade.getText());
            docente.setEndereco(endereco.getText());
            docente.setTelefoneUsuario(telefone.getText());
    }

    public Docentes unir(){
        String nomes = nome.getText();
        String enderecos = endereco.getText();
        String telefones = telefone.getText();
        String cidades = cidade.getText();
        Departamento dep = verificarDepartamento(cmbDepartamento.getSelectedItem().toString());
        TipoCurso titulacao = verificarTitulacao(cmbTitulacao.getSelectedItem().toString());
        Perfil perfil = verificarPerfil(cmbPerfil.getSelectedItem().toString());
        return new Docentes();
    }
     public void preencherDadosTela(Integer idDocente){
        DocentesControle funController = new DocentesControle(d.getEntity());
        Docentes fun = funController.consultarPorId(idDocente);
        nome.setText(fun.getNomeUsuario());
        idFuncionario.setText(idFuncionario.toString());
        endereco.setText(fun.getEndereco());
        telefone.setText(fun.getEndereco());   
        cmbDepartamento.setSelectedItem(fun.getDepartamentoFuncionario().name());
        cmbPerfil.setSelectedItem(fun.getPerfil().name());
        cmbTitulacao.setSelectedItem(fun.getTitulacaoFuncionario().name());
    }
     public void preencherCombos() {
        this.cmbDepartamento.removeAllItems();
        for (Departamento dep : Departamento.values()) {
            cmbDepartamento.addItem(dep.name());
        }
        this.cmbTitulacao.removeAllItems();
        for (TipoCurso titulacao : TipoCurso.values()) {
            cmbTitulacao.addItem(titulacao.name());
        }

        this.cmbPerfil.removeAllItems();
        for (Perfil perfil : Perfil.values()) {
            cmbPerfil.addItem(perfil.name());
        }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ID;
    private javax.swing.JTextField cidade;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JComboBox<String> cmbPerfil;
    private javax.swing.JComboBox<String> cmbTitulacao;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField idFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nome;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField telefone;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables




}
