package project.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import project.connection.ConectionSingleton;
import project.controller.NotaControle;
import project.model.Alunos;
import project.model.Notas;
import project.repository.DAORepositorio;
import project.repository.NotaDAO;
import project.repository.Tipo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yara Sereia do Cerrado
 */
public class StudentPerspective extends javax.swing.JFrame {
    Alunos aluno ;
    Notas nota ;
    Tipo persist;
    int tela;
    Menu menu ;
    CadastroAluno cadastroAlnno;
    CadastroDisciplina cadastroDisciplinas;
    ProfessorPerspective professorPerspective;
    NotaControle noteControle;
    /**
     * Creates new form Student
     */
    public StudentPerspective() {
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        setVisible(true);
        jTableNota.setAutoCreateRowSorter(true);
        persist = new Tipo (new NotaDAO(ConectionSingleton.getEntity()));
        listaNotas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNota = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        idDisciplina = new javax.swing.JFormattedTextField();
        idAAluno1 = new javax.swing.JFormattedTextField();
        Disci = new javax.swing.JButton();
        buscarIDAluno = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        consultar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nota I", "Nota II", "Nota Final", "Frequencia"
            }
        ));
        jTableNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableNotaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNota);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 253, 580, 337));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Disciplina:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        idDisciplina.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(idDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 113, 20));

        idAAluno1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(idAAluno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 113, -1));

        Disci.setText("...");
        Disci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisciActionPerformed(evt);
            }
        });
        getContentPane().add(Disci, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, 20));

        buscarIDAluno.setText("...");
        buscarIDAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(buscarIDAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 20));

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        consultar1.setText("consultar");
        getContentPane().add(consultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Onyx", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALUNO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel1)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id.setText("Aluno:");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
         Menu f = new Menu();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void jTableNotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNotaMousePressed
        // TODO add your handling code here:
            ProfessorPerspective notas = new ProfessorPerspective();
            notas.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jTableNotaMousePressed

    private void buscarIDAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDAlunoActionPerformed
        // TODO add your handling code here:
         ConsultarAlunos f = new ConsultarAlunos();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarIDAlunoActionPerformed

    private void DisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisciActionPerformed
        // TODO add your handling code here:
        ConsultarDisciplina f = new ConsultarDisciplina();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DisciActionPerformed

       public void listaNotas() {
        List<Notas> list = noteControle.listarNota();

        for (Notas nota : list) {

            DefaultTableModel model = (DefaultTableModel) jTableNota.getModel();

            String[] aux = new String[5];
            aux[0] = nota.getNota1();
            aux[1] = nota.getNota2();
            aux[2] = nota.getNotaFinal();
            aux[3] = nota.getFrequencia();
            model.addRow(aux);
        }
    }
       
           public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPerspective().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Disci;
    private javax.swing.JButton buscarIDAluno;
    private javax.swing.JButton consultar1;
    private javax.swing.JLabel id;
    private javax.swing.JFormattedTextField idAAluno1;
    private javax.swing.JFormattedTextField idDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNota;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables


}
